# Generated by Django 4.0.3 on 2022-04-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0002_submission_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='profiles/')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
