# Generated by Django 4.0.3 on 2022-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
