# Generated by Django 4.0.3 on 2022-04-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userinfo_first_name_userinfo_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
