# Generated by Django 4.0.3 on 2022-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_userinfo_first_name_remove_userinfo_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='profiles/')),
            ],
        ),
    ]
