# Generated by Django 4.0.3 on 2022-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_quiz_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sub_answer',
            field=models.CharField(choices=[('a', 'Option A'), ('b', 'Option B'), ('c', 'Option C'), ('d', 'Option D')], max_length=4, null=True),
        ),
    ]
